paths:
  /api/products:
    post:
      description: Add product.
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
            example:
              title: Producto 1
              description: Descripción del producto 1
              price: 100
              thumbnail:
                - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
              code: 1
              stock: 10
              category: Categoria 1
              status: true
      responses:
        "200":
          description: Returns the added product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                message: Producto agregado exitosamente.
                product:
                  _id: 60b4b0a9e6c3c2b4c8a7b8b2
                  title: Producto 1
                  description: Descripción del producto 1
                  price: 100
                  thumbnail:
                    - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                  code: 1
                  stock: 10
                  category: Categoria 1
                  status: true
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error
        "500":
          description: Internal server error.
          content:
            application/json:
              example:
                error: error