paths:
  /api/products:
    get:
      description: Get all products.
      tags:
        - Products
      responses:
        "200":
          description: Returns all products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                message: Productos encontrados.
                results:
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b2
                    title: Producto 1
                    description: Descripción del producto 1
                    price: 100
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 1
                    stock: 10
                    category: Categoria 1
                    status: true
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b3
                    title: Producto 2
                    description: Descripción del producto 2
                    price: 200
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 2
                    stock: 20
                    category: Categoria 2
                    status: true
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error
        "500":
          description: Internal server error.
          content:
            application/json:
              example:
                error: error

  /api/products/mockingProducts:
    get:
      description: Get mocking products.
      tags:
        - Products
      responses:
        "200":
          description: Returns mocking products.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              example:
                message: Productos falsos.
                results:
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b2
                    title: Producto falso 1
                    description: Descripción del producto falso 1
                    price: 100
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 1
                    stock: 10
                    category: Categoria 1
                    status: true
                  - _id: 60b4b0a9e6c3c2b4c8a7b8b3
                    title: Producto falso 2
                    description: Descripción del producto falso 2
                    price: 200
                    thumbnail:
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                      - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    code: 2
                    stock: 20
                    category: Categoria 2
                    status: true
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error
        "500":
          description: Internal server error.
          content:
            application/json:
              example:
                error: error

  /api/products/{productId}:
    get:
      description: Get product by ID.
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: Product ID
      responses:
        "200":
          description: Returns the desired product.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                message: Producto encontrado.
                product:
                  _id: 60b4b0a9e6c3c2b4c8a7b8b2
                  title: Producto 1
                  description: Descripción del producto 1
                  price: 100
                  thumbnail:
                    - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                    - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
                  code: 1
                  stock: 10
                  category: Categoria 1
                  status: true
        "400":
          description: Bad request.
          content:
            application/json:
              example:
                error: error
        "500":
          description: Internal server error.
          content:
            application/json:
              example:
                error: error